### ISSUE TITLE
Update Puppet submodules for `apt` and `mysql`

### ISSUE THREAD

**Issue by BronsonQuick** [Chassis/Chassis#762]
Currently there are some warnings for deprecations:
```
    default: Warning: ModuleLoader: module 'apt' has unresolved dependencies - it will only see those that are resolved. Use 'puppet module list --tree' to see information about modules\n   (file & line not available)
    default: Warning: ModuleLoader: module 'mysql' has unresolved dependencies - it will only see those that are resolved. Use 'puppet module list --tree' to see information about modules\n   (file & line not available)
    default: Warning: This method is deprecated, please use the stdlib validate_legacy function, with Pattern[]. There is further documentation for validate_legacy function in the README. at ["/vagrant/puppet/modules/mysql/manifests/db.pp", 17]:
    default:    (location: /vagrant/puppet/modules/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
    default: Warning: This method is deprecated, please use match expressions with Stdlib::Compat::Array instead. They are described at https://docs.puppet.com/puppet/latest/reference/lang_data_type.html#match-expressions. at ["/vagrant/puppet/modules/mysql/manifests/db.pp", 21]:
    default:    (location: /vagrant/puppet/modules/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
    default: Warning: This method is deprecated, please use match expressions with Stdlib::Compat::String instead. They are described at https://docs.puppet.com/puppet/latest/reference/lang_data_type.html#match-expressions. at ["/vagrant/puppet/modules/mysql/manifests/db.pp", 21]:
    default:    (location: /vagrant/puppet/modules/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
```

**Comment by BronsonQuick** [comment]
Turns out I forgot to update my submodules on an old Chassis box. 🙈
